### ISSUE TITLE
Cannot login after switch from internal to external MongoDB

### ISSUE THREAD

**Issue by alexanderharm** [goofball222/unifi#112]
As recommended in the logs I tried to migrate to an external MongoDB. So I stopped and removed my current unifi container and tried to bring up the new containers using this docker compose:

```
services:
  mongo:
    image: mongo:3.6
    container_name: unifi-db
    restart: unless-stopped
    volumes:
      - /volume1/docker/unifi/data/db:/data/db

  unifi:
    image: goofball222/unifi
    container_name: unifi
    restart: unless-stopped
    ports:
      - 3478:3478/udp
      - 8080:8080
      - 8443:8443
      - 8880:8880
      - 8843:8843
      - 6789:6789
      - 10001:10001/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/unifi/data:/usr/lib/unifi/data
      - /volume1/docker/unifi/logs:/usr/lib/unifi/logs
    environment:
      - DB_MONGO_LOCAL=true
      - UNIFI_DB_NAME=unifi
      - DB_MONGO_URI=mongodb://mongo:27017/unifi
      - STATDB_MONGO_URI=mongodb://mongo:27017/unifi_stat
      - TZ=Europe/Berlin
    depends_on:
      - mongo
```

Everything comes up nicely and reports as healthy. However, I'm unable to login into the unifi network controller. It reports that the username/password combination is wrong. Nothing in the logs. Switching back to the previous container and I can login just fine.

Any idea?

PS: Would be nice if the example for the docker-compose is a working config.  In your Docker images you use MongoDB v3.6. Maybe that can be added?
