### ISSUE TITLE
Bad Request This combination of host and port requires TLS.

### ISSUE THREAD

**Issue by m4dm4rtig4n** [goofball222/unifi#138]
## Reporting bugs/issues

Hello,

I have deploy your container in k8s cluster with ingress behind and redirect my ingress to 8443 but i have this error message :
```
Bad Request
This combination of host and port requires TLS.
```

I'm in HTTPS, but communication beetwen my ingress (traefik) and Unifi container is n HTTP.

me -> (https) -> ingress -> (http) -> container

It's possible to disable SSL Check if all SSL layer is supported behind container ?

**Comment by goofball222** [comment]
You're trying to send unencrypted http requests/traffic from Traefik to UniFi on a https port that requires SSL/TLS, thus the error.

Either send the requests to the UniFi standard http port 8080 or if UniFi is configured to redirect to https, configure Traefik to use https when communicating with the UniFi container(s). In that instance you might also need to set Traefik `serversTransport` to [`insecureSkipVerify`](https://doc.traefik.io/traefik/routing/overview/#insecureskipverify) to disable internal SSL certificate validation.

**Comment by m4dm4rtig4n** [comment]
Hello @goofball222 i have allready sent it :/
```
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: unifi
    kustomize.toolkit.fluxcd.io/namespace: unifi
  name: traefik-insecureskipverify
  namespace: unifi
spec:
  insecureSkipVerify: true
```
