### ISSUE TITLE
UniFI Video image

### ISSUE THREAD

**Issue by zyxep** [goofball222/unifi#19]
Hey,

Have you considered to make an automated build for Unifi Video?

**Comment by goofball222** [comment]
I'll into it, however I don't have any UniFi video equipment to test against so I would need community feedback on if it works or not.

Let me take a look at the system/software requirements and see what I can do. If I'm able to move ahead with it this will probably end up as another repository/project vs. a branch on this one.

**Comment by zyxep** [comment]
Sounds alright for me :)
I probably plan to buy a G3 pro camera, you didn't specify twitter anywhere so i made this issue as a request :D

**Comment by mikestecker** [comment]
@zyxep I'm using https://github.com/pducharme/UniFi-Video-Controller with my Docker setup, it works well. I have 4 cameras currently, planning on adding a few more.

**Comment by mikestecker** [comment]
@zyxep Also, if you wanted to see my `docker-compose.yml` portion for the video controller, here it is:

```
  unifi-video:
    container_name: unifi-video
    image: pducharme/unifi-video-controller
    network_mode: host
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    ports:
      - 1935:1935
      - 6666:6666
      - 7080:7080
      - 7442:7442
      - 7443:7443
      - 7444:7444
      - 7445:7445
      - 7446:7446
      - 7447:7447
    volumes:
      - ${USERDIR}/docker/unifi-video/config:/var/lib/unifi-video
      - /media/security/videos:/usr/lib/unifi-video/data/videos
      - ${USERDIR}/docker/unifi-video/logs:/var/log/unifi-video
```
